### PR TITLE
Re-set RABBITMQ_PLUGINS_DIR after INSTDIR is read from dialog

### LINKED ISSUE #28: Windows installer: plug-in installation directory ends up on drive C when installation directory is overridden to use another drive
When installing RabbitMQ server using the exe installer "rabbitmq-server-3.11.2.exe", if I change the install directory to the path in another disk such as "**D**:\Program Files\RabbitMQ Server", the RabbitMQ service will not be started normally but with error "system error 1067". After looking for the cause many hours, I found the cause was that the RabbitMQ plugins directory was not set correctly. The plugins directory was STILL placed to "**C**:\Program Files\RabbitMQ Server" after the installation although I had changed the install directory.
The recent windows exe installer may have the same problem, not just the one "rabbitmq-server-3.11.2.exe".
Please have a check.

Platform env.: Windows 10 or Windows 11

### PR DESCRIPTION
**Pull request by lukebakken**
Follow-up to #15

Fixes #28 

cc @inikulshin

### CODE REVIEW

**Review by dumbbell — APPROVED** [review]
This looks good to me. @inikulshin suggested to move the code instead, it's probably a good idea.

**Review by dumbbell — APPROVED** [review]

**Comment by michaelklishin** [comment]
Like https://github.com/rabbitmq/rabbitmq-packaging/pull/15, this has to be backported as far as `v3.9.x`

**Comment by michaelklishin** [comment]
@mergifyio backport v3.11.x v3.10.x v3.9.x

**Comment by lukebakken** [comment]
Thanks @dumbbell and @michaelklishin

**Pull request merged**
